/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/ColorPalette`; params?: Router.UnknownInputParams; } | { pathname: `/../src/services/HighlightService`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favorites` | `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chapters/[book]` | `/chapters/[book]`, params: Router.UnknownInputParams & { book: string | number; } } | { pathname: `${'/(tabs)'}/reading/[book]/[chapter]` | `/reading/[book]/[chapter]`, params: Router.UnknownInputParams & { book: string | number;chapter: string | number; } } | { pathname: `${'/(tabs)'}/verses/[book]/[chapter]` | `/verses/[book]/[chapter]`, params: Router.UnknownInputParams & { book: string | number;chapter: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/favorites`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/ColorPalette`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/services/HighlightService`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/favorites` | `/favorites`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chapters/[book]` | `/chapters/[book]`, params: Router.UnknownOutputParams & { book: string; } } | { pathname: `${'/(tabs)'}/reading/[book]/[chapter]` | `/reading/[book]/[chapter]`, params: Router.UnknownOutputParams & { book: string;chapter: string; } } | { pathname: `${'/(tabs)'}/verses/[book]/[chapter]` | `/verses/[book]/[chapter]`, params: Router.UnknownOutputParams & { book: string;chapter: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/favorites${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/../src/components/ColorPalette${`?${string}` | `#${string}` | ''}` | `/../src/services/HighlightService${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/favorites${`?${string}` | `#${string}` | ''}` | `/favorites${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/ColorPalette`; params?: Router.UnknownInputParams; } | { pathname: `/../src/services/HighlightService`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favorites` | `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `${'/(tabs)'}/chapters/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/chapters/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/reading/${Router.SingleRoutePart<T>}/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/reading/${Router.SingleRoutePart<T>}/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/verses/${Router.SingleRoutePart<T>}/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/verses/${Router.SingleRoutePart<T>}/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(tabs)'}/chapters/[book]` | `/chapters/[book]`, params: Router.UnknownInputParams & { book: string | number; } } | { pathname: `${'/(tabs)'}/reading/[book]/[chapter]` | `/reading/[book]/[chapter]`, params: Router.UnknownInputParams & { book: string | number;chapter: string | number; } } | { pathname: `${'/(tabs)'}/verses/[book]/[chapter]` | `/verses/[book]/[chapter]`, params: Router.UnknownInputParams & { book: string | number;chapter: string | number; } };
    }
  }
}
